### ISSUE TITLE
extract_kernel input

### ISSUE THREAD

**Issue by pote** [drsn0w/chromebook_kernel_tools#1]
Hey! Not sure if this is the right place to bring up questions or if you prefer irc/some other form, but I've been fiddling around with my C200 to no avail for days, so here goes.

I'm reading the scripts to get a feel of what the process implies - and my Linux knowledge is very limited , right now extract_kernel is hardcoded to use `if=/dev/mmcblk0p2`, which doesn't exist in my machine. I only have `/dev/mmcblk0p1` (11G, mounted at `/home`) and `/dev/mmcblk0p8` (13M, mounted at `/usr/share/oem`.

I'm guessing In my case I should be running `sudo dd if=/dev/mmcblk0p1 of=kernel2`, but I wanted to check with you to be completely sure, am I on the right track?

**Comment by drsn0w** [comment]
No, mmcblk0p2 is the partition where the first kernel is stored. It shouldn't be mounted at all, try running `lsblk` and you should be able to see all partitions, I believe Chrome OS usually has 12.

**Comment by pote** [comment]
Ah, got it, I was only looking at mounted partitions, thanks for your help!

**Comment by drsn0w** [comment]
No problem, happy to help. If you have any more issues, feel free to email me at drsn0w at outlook dot com (:
