### ISSUE TITLE
Trying to install on a C200 chromebook

### ISSUE THREAD

**Issue by grosdod** [drsn0w/chromebook_kernel_tools#2]
I tried to install arch linux using your method on my C200. Unfortunately, the file /usr/share/vboot/devkeys/kernel_data_key.vprivk does not exists on it.

Here are the files of this directory : 

dev_firmware_data_key.vbprivk  ec_root_key.vbprivk        installer_kernel_data_key.vbprivk  kernel_subkey.vbprivk             recovery_key.vbprivk
dev_firmware_data_key.vbpubk   ec_root_key.vbpubk         installer_kernel_data_key.vbpubk   kernel_subkey.vbpubk              recovery_key.vbpubk
dev_firmware.keyblock          firmware_bmpfv.bin         installer_kernel.keyblock          key.versions                      root_key.vbprivk
ec_data_key.vbprivk            firmware_data_key.vbprivk  kernel_data_key.vbprivk            recovery_kernel_data_key.vbprivk  root_key.vbpubk
ec_data_key.vbpubk             firmware_data_key.vbpubk   kernel_data_key.vbpubk             recovery_kernel_data_key.vbpubk
ec.keyblock                    firmware.keyblock          kernel.keyblock                    recovery_kernel.keyblock

Any idea ?

Thanks in advance.

**Comment by jdloft** [comment]
It should be `kernel_data_key.vbprivk`.

**Comment by severen** [comment]
> Don't you love when someone randomly comments on a year-old issue??

\- web7root
